### ISSUE TITLE
ブログカードコンポーネント詳細設計

### ISSUE THREAD

**Issue by shogyomujo11** [akanesi05/teamsdev_17_2#16]
https://github.com/akanesi05/teamsdev_17_2/wiki/%E7%94%BB%E9%9D%A2%E8%A9%B3%E7%B4%B0%E8%A8%AD%E8%A8%88%E6%9B%B8%E3%82%B5%E3%83%B3%E3%83%97%E3%83%AB
を参考にして
https://github.com/akanesi05/teamsdev_17_2/wiki/%E3%83%96%E3%83%AD%E3%82%B0%E3%82%AB%E3%83%BC%E3%83%89%E3%82%B3%E3%83%B3%E3%83%9D%E3%83%BC%E3%83%8D%E3%83%B3%E3%83%88
にブログカードコンポーネントの詳細設計を作成してください。

【ゴール】
https://github.com/akanesi05/teamsdev_17_2/wiki/%E3%83%96%E3%83%AD%E3%82%B0%E3%82%AB%E3%83%BC%E3%83%89%E3%82%B3%E3%83%B3%E3%83%9D%E3%83%BC%E3%83%8D%E3%83%B3%E3%83%88
にブログカードコンポーネントのコンポーネント、アクションがもれなく列挙されること。

**Comment by rain2124** [comment]
@shogyomujo11 
どのコンポーネントか不明のためキャプチャいただけないでしょうか。
mtgの際に会話があった①でしょうか。それともブログカードとなると②となるでしょうか。
①https://gyazo.com/7d70cd97a9c70e674fd696d294b94099
②https://gyazo.com/c20725fed372c23a560a456c6a145e98
※ ①前提にて一応作成いたしましたのでご確認お願いいたします。
https://github.com/akanesi05/teamsdev_17_2/wiki/%E3%83%96%E3%83%AD%E3%82%B0%E3%82%AB%E3%83%BC%E3%83%89%E3%82%B3%E3%83%B3%E3%83%9D%E3%83%BC%E3%83%8D%E3%83%B3%E3%83%88

**Comment by rain2124** [comment]
@shogyomujo11 
更新しましたのでご確認お願いします。
https://github.com/akanesi05/teamsdev_17_2/wiki/%E3%83%96%E3%83%AD%E3%82%B0%E3%82%AB%E3%83%BC%E3%83%89%E3%82%B3%E3%83%B3%E3%83%9D%E3%83%BC%E3%83%8D%E3%83%B3%E3%83%88

**Comment by rain2124** [comment]
# BlogView画面詳細設計 MORE POST

## 画面概要
BLOG詳細画面表示画面 MORE POST
カレント記事を除いた最新3件を表示するものとする

## コンポーネント一覧
| ID | コンポーネント名 | 種別 | 値:ラベル |
| :-- | :-- | :-- | :-- |
| C-01 | MOREPOST TITLE | タイトル | テキスト |
| C-02 | MOREPOST IMAGE | 画像 | 画像URL |
| C-03 | MOREPOST LINK | リンク | URL |

## アクション一覧
| ID | トリガー | イベント |
| :-- | :-- | :-- |
| A-01 | C-03 | onClick |

### A-01
1. MOREPOSTの記事idを取得し、blog/[記事ID] のURLに遷移させる

**Comment by shogyomujo11** [comment]
ああすいません、②のつもりでした。
書いてもらったものも無駄ではないのでそのまま残してもらって、別のwikiに作成をお願いします。

**Comment by shogyomujo11** [comment]
問題なさそうです！　ありがとうございました。
クローズします。
