### ISSUE TITLE
Supabase上にDBを作成する

### ISSUE THREAD

**Issue by shogyomujo11** [akanesi05/teamsdev_17_2#18]
テーブル定義書通りのデータベースをSupabaseに作成してください。
Supabaseはご自身のアカウントで新規登録してください。無料枠で大丈夫です。
初期の動作確認用にダミーデータを2、3個入れておいてください。
一通りできたら他のチームメンバーを招待してください。

【ゴール】
Supabase上のダッシュボードでデータベースの中身が見られる。
テーブル定義書通りのテーブルが作られている。

【参考サイト】
テーブル定義書
https://www.figma.com/board/ahrYNBWFON2rr9Eop2h2N4/%E3%83%86%E3%83%BC%E3%83%96%E3%83%AB%E5%AE%9A%E7%BE%A9%E6%9B%B8%2FER%E5%9B%B3?node-id=0-1&node-type=canvas

Supabaseにデータベースを作る
https://qiita.com/pikimaru/items/5e51d36250c288b8b6dc

Supabaseにメンバーを招待する
https://zenn.dev/joo_hashi/articles/83043697718ead

**Comment by shogyomujo11** [comment]
Figmaのテーブル定義書を正としてレビューします。
https://www.figma.com/board/ahrYNBWFON2rr9Eop2h2N4/%E3%83%86%E3%83%BC%E3%83%96%E3%83%AB%E5%AE%9A%E7%BE%A9%E6%9B%B8%2FER%E5%9B%B3?node-id=0-1&p=f&t=G6CeT4gumc71k8XW-0

# users
* `id`の型はstringのところがint8になっています。
# posts
* `id`の型はstringのところがint8になっています。
* `created_at`の型がtimestamptzになってますがtimestampにできますか？
# comments
* `id`の型はstringのところがint8になっています。
* `created_at`の型がtimestamptzになってますがtimestampにできますか？
# categories
* テーブル名が`categorise`とタイポしてます。
* `id`の型はstringのところがint8になっています。
* `created_at`の型がtimestamptzになってますがtimestampにできますか？

**Comment by akanesi05** [comment]
@shogyomujo11 

usersを画像のように変更すればよろしいですか、変更するとエラーが表示されます。データを作り直した方がいいですか
各テーブルのtimestamptzをtimestampに変更致しました。categoriesのテーブル名を正しいものに訂正いたしました。

[![Image from Gyazo](https://i.gyazo.com/b1c96c8e3a964c07d21a4d212480ad88.png)](https://gyazo.com/b1c96c8e3a964c07d21a4d212480ad88)

**Comment by shogyomujo11** [comment]
問題ないと思います！
これでDB構築は完了です。お疲れ様でした。
