### ISSUE TITLE
SignUp画面詳細設計

### ISSUE THREAD

**Issue by shogyomujo11** [akanesi05/teamsdev_17_2#2]
https://github.com/akanesi05/teamsdev_17_2/wiki/%E7%94%BB%E9%9D%A2%E8%A9%B3%E7%B4%B0%E8%A8%AD%E8%A8%88%E6%9B%B8%E3%82%B5%E3%83%B3%E3%83%97%E3%83%AB
を参考にして
https://github.com/akanesi05/teamsdev_17_2/wiki/SignUp%E7%94%BB%E9%9D%A2
にSignUp画面の詳細設計を作成してください。

【ゴール】
https://github.com/akanesi05/teamsdev_17_2/wiki/SignUp%E7%94%BB%E9%9D%A2
にSignUp画面のコンポーネント、アクションがもれなく列挙されること。

**Comment by akanesi05** [comment]
@shogyomujo11   　途中まで作成いたしました。確認をお願いいたします

**Comment by shogyomujo11** [comment]
# コンポーネント一覧
* `C-05`、`C-06` コンポーネント名に `Sain` とありますが `Sign` のタイポですね。

# アクション一覧
* `A-02`に`C-02`、`C-03`、`C-04`のアクションをまとめたのですね。ただIDはユニークに保っておきたいので、それぞれ別ID振って3アクションに分割してもらえますか。
* `A-03`はまだ途中ですかね。このあたりはSupabaseのDocumentを貼って終わりでもよいです。
* `A-04`はClickしたらどんなURLに飛ぶかも書いておきましょう。

**Comment by shogyomujo11** [comment]
# アクション一覧
* `A-02`、`A-03`、`A-04`に分割してもらったのはいいのですが、以前の記述にあった最大文字数のバリデーションも復活させてください。
* `A-06`のアクションを記載してください。
* `A-03 create対応表`のカラム名がサンプルのままになっています。あと`A-03`ではなく`A-05`ですね。
