### ISSUE TITLE
ブログカードコンポーネントのガワ作成

### ISSUE THREAD

**Issue by shogyomujo11** [akanesi05/teamsdev_17_2#28]
https://github.com/akanesi05/teamsdev_17_2/issues/16
がクローズしたら取りかかってください

ブログカードコンポーネントを実装する。

「ガワ」とは下記のような状態を指す。
・コンポーネント定義を行い、単にベタうちhtmlをreturnするだけでよい。
・ただし画面詳細設計wikiでコンポーネント一覧に列挙されている部品はすべて載せておくこと。
・state管理だとかデータ取得とかイベントハンドラだとかはまだ実装しなくてよい。
・スタイル当ても必須ではない。ただしスタイル当てながらの方がやりやすいのであれば一緒にやってしまってもよい。

【ゴール】
必要であればダミー画面コンポーネントを用意してそこにブログカードを配置し、Next.jsを起動して既定のURLにアクセスしたらブログカードが表示されること。

**Comment by hy-tanebi** [comment]
ブログカードのガワ作成しましたので、ご確認お願いいたします。
https://github.com/akanesi05/teamsdev_17_2/pull/37
