### ISSUE TITLE
Home画面詳細設計

### ISSUE THREAD

**Issue by shogyomujo11** [akanesi05/teamsdev_17_2#3]
https://github.com/akanesi05/teamsdev_17_2/wiki/%E7%94%BB%E9%9D%A2%E8%A9%B3%E7%B4%B0%E8%A8%AD%E8%A8%88%E6%9B%B8%E3%82%B5%E3%83%B3%E3%83%97%E3%83%AB
を参考にして
https://github.com/akanesi05/teamsdev_17_2/wiki/Home%E7%94%BB%E9%9D%A2
にHome画面の詳細設計を作成してください。

【ゴール】
https://github.com/akanesi05/teamsdev_17_2/wiki/Home%E7%94%BB%E9%9D%A2
にHome画面のコンポーネント、アクションがもれなく列挙されること。

**Comment by hy-tanebi** [comment]
Home画面の詳細設計をWikiに追記しました。

- 作業内容: コンポーネントとアクションの詳細をMarkdown形式で記述
- 編集したページ: [Home画面詳細設計](https://github.com/akanesi05/teamsdev_17_2/wiki/Home%E7%94%BB%E9%9D%A2)

ご確認お願いいたします。

**Comment by shogyomujo11** [comment]
* `C-01`～`C-04`はヘッダーコンポーネントの要素なので、ここでは「`C-01`　ヘッダー」のみで構いません。
    * 今ある記述はヘッダーコンポーネント詳細設計wikiに転記しておきましょう。
    * `A-01`～`A-03`のアクションも同様に。
* `C-08`、`A-06`もページネーションコンポーネント詳細設計wikiに移しておいてください。
* アクション一覧のトリガーでコンポーネントを参照するときは`C-01`のようにコンポーネントIDを使用してください。
* アクション一覧に初期表示時のアクションが必要です。記事一覧はどのテーブルからどういう並び順でいくつ取得するか、の条件まで書いてください。
* `A-04` 「該当記事」だけでは条件が曖昧ですね。
* `A-05` 「記事の詳細ページを表示」だけではなく具体的なURLも書いておくと実装者に優しいです。

**Comment by hy-tanebi** [comment]
詳細ありがとうございます。
修正しましたので、ご確認お願いいたします。

- [Home画面詳細設計wiki](https://github.com/akanesi05/teamsdev_17_2/wiki/Home%E7%94%BB%E9%9D%A2)


- [へッダーコンポーネント詳細設計wiki](https://github.com/akanesi05/teamsdev_17_2/wiki/%E3%83%98%E3%83%83%E3%83%80%E3%83%BC%E3%82%B3%E3%83%B3%E3%83%9D%E3%83%BC%E3%83%8D%E3%83%B3%E3%83%88
)

- [ページネーションコンポーネント詳細設計wik](https://github.com/akanesi05/teamsdev_17_2/wiki/%E3%83%9A%E3%83%BC%E3%82%B8%E3%83%8D%E3%83%BC%E3%82%B7%E3%83%A7%E3%83%B3%E3%82%B3%E3%83%B3%E3%83%9D%E3%83%BC%E3%83%8D%E3%83%B3%E3%83%88)

**Comment by shogyomujo11** [comment]
ありがとうございました！　良さそうですのでクローズします。
