### ISSUE TITLE
BlogView画面詳細設計

### ISSUE THREAD

**Issue by shogyomujo11** [akanesi05/teamsdev_17_2#4]
https://github.com/akanesi05/teamsdev_17_2/wiki/%E7%94%BB%E9%9D%A2%E8%A9%B3%E7%B4%B0%E8%A8%AD%E8%A8%88%E6%9B%B8%E3%82%B5%E3%83%B3%E3%83%97%E3%83%AB
を参考にして
https://github.com/akanesi05/teamsdev_17_2/wiki/BlogView%E7%94%BB%E9%9D%A2
にBlogView画面の詳細設計を作成してください。

【ゴール】
https://github.com/akanesi05/teamsdev_17_2/wiki/BlogView%E7%94%BB%E9%9D%A2
にBlogView画面のコンポーネント、アクションがもれなく列挙されること。

**Comment by rain2124** [comment]
# BlogView画面詳細設計
|        <div align="left">PC画面</div>       |         <div align="left">SP画面</div>        |
|:-----------|:------------|
| ![Blog View](https://github.com/user-attachments/assets/77ad5519-5eb1-4d01-a4e5-bf79c40d94c1) | ![Blog View - Mobile](https://github.com/user-attachments/assets/35c5aaa2-73ba-45a6-8a60-9dff9dc92577) |
```
補足
上記デザインをもとに詳細設計に起こしたという前提とします。
```
## 画面概要
BLOG詳細画面表示画面
```
補足
大まかに下記3項目表示するページ
・CURRENT 詳細画面
・CURRENT BLOGを除いた3件表示
・COMMENTS 追加機能
```
## URL
/blog/[id]

## コンポーネント一覧
| ID | コンポーネント名 | 種別 | 値:ラベル |
| :-- | :-- | :-- | :-- |
| C-01 | ヘッダー | ヘッダー | - |
| C-02 | タイトル | タイトル | 記事タイトル |
| C-03 | アイコン | 画像 | 製作者アイコン画像 |
| C-04 | 画像 | 画像 | 記事画像 |
| C-05| テキスト | テキスト | 記事テキスト |
| C-06| Comments 入力 | input | コメント入力内容 |
| C-07| Comments Addボタン | button | コメント入力追加ボタン |
| C-08| Comments 投稿リスト アイコン | 画像 | Comments投稿者のアイコン |
| C-09| Comments 投稿リスト 名前 | テキスト | Comments投稿者の名前 |
| C-10| Comments 投稿リスト テキスト | 画像 | Comments投稿者のテキスト |
| C-11| Comments 投稿リスト 投稿時間 | テキスト | Comments投稿者の投稿時間 |

## アクション一覧
| ID | トリガー | イベント |
| :-- | :-- | :-- |
| A-01 | C-06入力 | onChange |
| A-02 | C-07押下 | onClick |

### A-01
commentsテーブルを参照し下記を実行する
1. photos.id = URLのパスパラメータで渡されたid とする
2. id == posts.id と入力者のuseridを紐付けcommentsテーブルにinput内容の値を渡すものとする

### A-02
1. A-01にて記述している内容を実行し、Commentsリストの一番前に追加するボタン
　1. C-08 = 投稿者のidに紐づくユーザーアイコンを表示
　2. C-08 = 投稿者のidに紐づくユーザーネームを表示
　3. C-09 = C-06にて入力されたコメントを表示
　4. C-10 = C-07を押下した際の時間を取得しそれを時間を表示

### commentsテーブル
| カラム | 値 |
| :-- | :-- |
| commentTitle | コメント内容 |
| commentDate | 入稿日時 |

**Comment by shogyomujo11** [comment]
* `C-06`、`C-07`はMorePostsコンポーネントとするので、新しいwikiページを作ってそちらにコンポーネント一覧、アクション一覧をまとめてください。
* MorePostsコンポーネントにonClickイベントが必要ではないでしょうか？
    * クリックしたらそのBlogView画面に飛ばしてください。
* アクション一覧に初期表示時のアクションが必要です。
    1. URLのパスパラメータからidを取得する
    2. id == posts.id を条件にpostsレコードを取得して各コンポーネントに表示する
    3. MorePostsを取得して表示する
    4. Commentsを取得して表示する
* `A-02`に書かれているのはComments保存後の挙動ですかね。Commentsテーブルの各カラムに何を入れるかのINSERT対応表もあると実装者が惑いません。

**Comment by rain2124** [comment]
@shogyomujo11
更新しましたのでご確認お願いします。
https://github.com/akanesi05/teamsdev_17_2/wiki/%E3%83%96%E3%83%AD%E3%82%B0%E3%82%AB%E3%83%BC%E3%83%89%E3%82%B3%E3%83%B3%E3%83%9D%E3%83%BC%E3%83%8D%E3%83%B3%E3%83%88

**Comment by shogyomujo11** [comment]
ありがとうございました。問題なさそうです！
クローズします。
