### ISSUE TITLE
Profile画面詳細設計

### ISSUE THREAD

**Issue by shogyomujo11** [akanesi05/teamsdev_17_2#6]
https://github.com/akanesi05/teamsdev_17_2/wiki/%E7%94%BB%E9%9D%A2%E8%A9%B3%E7%B4%B0%E8%A8%AD%E8%A8%88%E6%9B%B8%E3%82%B5%E3%83%B3%E3%83%97%E3%83%AB
を参考にして
https://github.com/akanesi05/teamsdev_17_2/wiki/Profile%E7%94%BB%E9%9D%A2
にProfile画面の詳細設計を作成してください。

【ゴール】
https://github.com/akanesi05/teamsdev_17_2/wiki/Profile%E7%94%BB%E9%9D%A2
にProfile画面のコンポーネント、アクションがもれなく列挙されること。

**Comment by hy-tanebi** [comment]
こちら記入しましたので、ご確認お願いいたします。

https://github.com/akanesi05/teamsdev_17_2/wiki/Profile%E7%94%BB%E9%9D%A2

**Comment by shogyomujo11** [comment]
ありがとうございました。問題なさそうです！
クローズします。
